[licenses]
# Only allow licenses compatible with AGPL
clarify = []
allow = [
    "AGPL-3.0-only",
    "GPL-3.0-only",
    "LGPL-3.0-only",
    "MIT",          # MIT is compatible with AGPL
    "Apache-2.0",   # Apache 2.0 is compatible with AGPL
    "BSD-3-Clause", # BSD-3-Clause is compatible with AGPL
    "ISC",         # ISC is compatible with AGPL
    "CC0-1.0",     # CC0 is compatible with AGPL
    "Unicode-3.0", # Used by unicode-ident crate
]

# Ensure every crate has a valid license file
private = { ignore = true }
confidence-threshold = 0.8

# Don't warn about allowed licenses that aren't currently used
unused-allowed-license = "allow"
