name: _release
on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate Release Notes
      id: changelog
      uses: orhun/git-cliff-action@v2
      with:
        config: cliff.toml
        args: --latest --strip header

    - name: Version
      shell: bash
      env:
        RELEASE_TAG: ${{ github.ref }}
      run: |
        sed -i "s/0\\.0\\.0-git/${RELEASE_TAG##*\/v}/" Cargo.toml
        sed -i "s/0\\.0\\.0-git/${RELEASE_TAG##*\/v}/" Cargo.lock

    - name: Download Linux Build
      uses: actions/download-artifact@v4
      with:
        name: gitopolis-linux-x86_64

    - name: Download Windows Build
      uses: actions/download-artifact@v4
      with:
        name: gitopolis-windows-x86_64

    - name: Download macOS Build
      uses: actions/download-artifact@v4
      with:
        name: gitopolis-macos-x86_64

    - name: Generate SHA256 Checksums
      run: |
        sha256sum gitopolis-linux-x86_64.tar.gz gitopolis-windows-x86_64.zip gitopolis-macos-x86_64.tar.gz > SHA256SUMS.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.changelog.outputs.content }}
        files: |
          gitopolis-linux-x86_64.tar.gz
          gitopolis-windows-x86_64.zip
          gitopolis-macos-x86_64.tar.gz
          SHA256SUMS.txt
