name: build-tag

on:
  push:
    tags: [ "v*" ]

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml
    with:
      release_tag: ${{ github.ref_name }}

  release:
    needs: ci
    uses: ./.github/workflows/_release.yml
    with:
      release_tag: ${{ github.ref_name }}
